/**
 * Lucien API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateUserDto { 
    firstName?: string | null;
    lastName?: string | null;
    userName?: string | null;
    gender?: number | null;
    dateOfBirth?: string | null;
    email?: string | null;
    phone?: string | null;
    photo?: string | null;
    address?: string | null;
    password?: string | null;
    passwordHash?: string | null;
    roleId?: string | null;
}

