/**
 * Lucien API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FileResultDto { 
    fileContent?: string | null;
    contentType?: string | null;
    fileName?: string | null;
}

