/**
 * Lucien API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PermissionDto } from './permissionDto';


export interface PermissionDtoIReadOnlyCollectionResultDto { 
    data?: Array<PermissionDto> | null;
    message?: string | null;
    isSuccess?: boolean;
    statusCode?: number | null;
}

