/**
 * Lucien API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterDto { 
    email?: string | null;
    phone?: string | null;
    roleId?: string | null;
    password?: string | null;
    confirmPassword?: string | null;
}

