/**
 * Lucien API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleDto } from './roleDto';


export interface RoleDtoResultDto { 
    data?: RoleDto;
    message?: string | null;
    isSuccess?: boolean;
    statusCode?: number | null;
}

