/**
 * Lucien API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RoleDto { 
    readonly id?: string;
    readonly name?: string | null;
    readonly createdAt?: string;
    readonly updatedAt?: string | null;
    readonly createdBy?: string | null;
    readonly updatedBy?: string | null;
}

