/**
 * Lucien API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleDtoPagedResultDto } from './roleDtoPagedResultDto';


export interface RoleDtoPagedResultDtoResultDto { 
    data?: RoleDtoPagedResultDto;
    message?: string | null;
    isSuccess?: boolean;
    statusCode?: number | null;
}

