/**
 * Lucien API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StringIReadOnlyCollectionResultDto { 
    data?: Array<string> | null;
    message?: string | null;
    isSuccess?: boolean;
    statusCode?: number | null;
}

