/**
 * Lucien API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TokenDto } from './tokenDto';


export interface TokenDtoResultDto { 
    data?: TokenDto;
    message?: string | null;
    isSuccess?: boolean;
    statusCode?: number | null;
}

