/**
 * Lucien API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateCardDto { 
    name?: string | null;
    gender?: number;
    dateOfBirth?: string;
    email?: string | null;
    phone?: string | null;
    photo?: string | null;
    address?: string | null;
}

