/**
 * Lucien API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleDto } from './roleDto';


export interface UserDto { 
    readonly id?: string;
    readonly firstName?: string | null;
    readonly lastName?: string | null;
    readonly userName?: string | null;
    readonly gender?: number | null;
    readonly dateOfBirth?: string | null;
    readonly email?: string | null;
    readonly phone?: string | null;
    readonly photo?: string | null;
    readonly address?: string | null;
    passwordHash?: string | null;
    roleId?: string | null;
    role?: RoleDto;
}

