/**
 * Lucien API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDtoPagedResultDto } from './userDtoPagedResultDto';


export interface UserDtoPagedResultDtoResultDto { 
    data?: UserDtoPagedResultDto;
    message?: string | null;
    isSuccess?: boolean;
    statusCode?: number | null;
}

